apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "alert-manager-webhook.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "alert-manager-webhook.serviceAccountName" . }}
  apiGroup: ""
roleRef:
  kind: Role
  name: {{ include "alert-manager-webhook.fullname" . }}
  apiGroup: ""