apiVersion: v1
kind: Service
metadata:
  name: alert-webhook
  labels:
    app: alert-webhook
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: alert-webhook
    protocol: TCP
    targetPort: http
  selector:
    app: alert-webhook