apiVersion: v1
kind: Service
metadata:
  name: {{ include "alert-manager-webhook.fullname" . }}
  labels:
    {{- include "alert-manager-webhook.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: alert-webhook
    protocol: TCP
    targetPort: http
  selector:
    {{- include "alert-manager-webhook.selectorLabels" . | nindent 4 }}