apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - dcgm-exporter.yaml
  - service-monitor.yaml

namespace: gpu-metrics

commonLabels:
  app: gpu-metrics